-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 15:43:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thewinegame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thewinegame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thewinegame` DEFAULT CHARACTER SET utf8 ;
USE `thewinegame` ;

-- -----------------------------------------------------
-- Table `thewinegame`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `region_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_region_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_region_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `thewinegame`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`producer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`wine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `vintage` INT NULL,
  `size` INT NULL,
  `producer_id` INT NULL,
  `name` VARCHAR(90) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wine_color_idx` (`color_id` ASC),
  INDEX `fk_wine_region1_idx` (`region_id` ASC),
  INDEX `fk_wine_producer1_idx` (`producer_id` ASC),
  CONSTRAINT `fk_wine_color`
    FOREIGN KEY (`color_id`)
    REFERENCES `thewinegame`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `thewinegame`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_producer1`
    FOREIGN KEY (`producer_id`)
    REFERENCES `thewinegame`.`producer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`variety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`variety` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`wine_variety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`wine_variety` (
  `wine_id` INT NOT NULL,
  `variety_id` INT NOT NULL,
  INDEX `fk_wine_variety_wine1_idx` (`wine_id` ASC),
  INDEX `fk_wine_variety_variety1_idx` (`variety_id` ASC),
  PRIMARY KEY (`variety_id`, `wine_id`),
  CONSTRAINT `fk_wine_variety_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `thewinegame`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_variety_variety1`
    FOREIGN KEY (`variety_id`)
    REFERENCES `thewinegame`.`variety` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`rating_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`rating_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`rating` (
  `wine_id` INT NOT NULL,
  `rating_type_id` INT NOT NULL,
  `value` INT NULL,
  INDEX `fk_rating_wine1_idx` (`wine_id` ASC),
  INDEX `fk_rating_rating_type1_idx` (`rating_type_id` ASC),
  PRIMARY KEY (`wine_id`, `rating_type_id`),
  CONSTRAINT `fk_rating_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `thewinegame`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_rating_type1`
    FOREIGN KEY (`rating_type_id`)
    REFERENCES `thewinegame`.`rating_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(360) NULL,
  `wine_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_wine1_idx` (`wine_id` ASC),
  CONSTRAINT `fk_image_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `thewinegame`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thewinegame`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thewinegame`.`price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wine_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `value` FLOAT NULL,
  `currency` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_price_wine1_idx` (`wine_id` ASC),
  INDEX `fk_price_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_price_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `thewinegame`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `thewinegame`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- INSERT `thewinegame`.`store`
-- -----------------------------------------------------

INSERT INTO store (name, url) VALUES ('wine.com', 'https://www.wine.com/');
INSERT INTO store (name, url) VALUES ('Astor Wines & Spirits', 'https://www.astorwines.com/');
INSERT INTO store (name, url) VALUES ('Bottlerocket', 'https://bottlerocket.com/');
INSERT INTO store (name, url) VALUES ('Italian Wine Merchants', 'https://www.italianwinemerchants.com/');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
